<style>
/* Generated by http://css.spritegen.com CSS Sprite Generator */

.ground2, .ground1, .bush1, .bush2, .tree1, 
.tree2, .cliff-left, .cliff-right
{ display: inline-block; background: url('/static/img/sprites/tileset.png') no-repeat; overflow: hidden; text-indent: -9999px; text-align: left; }

.ground2 { background-position: -5px -0px; width: 128px; height: 101px; }
.ground1 {
  background-position: -5px -106px; width: 96px; height: 105px;
  &--repeat {
    background: url('/static/img/ground1.png') repeat-x;
    width: 100%;
    height: 105px;
  }
}

.bush1 { background-position: -5px -216px; width: 74px; height: 32px; }
.bush2 { background-position: -5px -253px; width: 74px; height: 32px; }
.tree1 { background-position: -5px -290px; width: 50px; height: 116px; }
.tree2 { background-position: -60px -290px; width: 50px; height: 116px; }
.cliff-left { background-position: -5px -411px; width: 27px; height: 104px; }
.cliff-right { background-position: -37px -411px; width: 27px; height: 104px; }

body {
      background: rgba(135,208,208,1);
    background: -moz-linear-gradient(top, rgba(135,208,208,1) 0%, rgba(135,208,208,1) 25%, rgba(159,211,201,1) 25%, rgba(159,211,201,1) 50%, rgba(182,213,195,1) 50%, rgba(182,213,195,1) 75%, rgba(194,215,192,1) 75%, rgba(194,215,192,1) 100%);
    background: -webkit-gradient(left top, left bottom, color-stop(0%, rgba(135,208,208,1)), color-stop(25%, rgba(135,208,208,1)), color-stop(25%, rgba(159,211,201,1)), color-stop(50%, rgba(159,211,201,1)), color-stop(50%, rgba(182,213,195,1)), color-stop(75%, rgba(182,213,195,1)), color-stop(75%, rgba(194,215,192,1)), color-stop(100%, rgba(194,215,192,1)));
    background: -webkit-linear-gradient(top, rgba(135,208,208,1) 0%, rgba(135,208,208,1) 25%, rgba(159,211,201,1) 25%, rgba(159,211,201,1) 50%, rgba(182,213,195,1) 50%, rgba(182,213,195,1) 75%, rgba(194,215,192,1) 75%, rgba(194,215,192,1) 100%);
    background: -o-linear-gradient(top, rgba(135,208,208,1) 0%, rgba(135,208,208,1) 25%, rgba(159,211,201,1) 25%, rgba(159,211,201,1) 50%, rgba(182,213,195,1) 50%, rgba(182,213,195,1) 75%, rgba(194,215,192,1) 75%, rgba(194,215,192,1) 100%);
    background: -ms-linear-gradient(top, rgba(135,208,208,1) 0%, rgba(135,208,208,1) 25%, rgba(159,211,201,1) 25%, rgba(159,211,201,1) 50%, rgba(182,213,195,1) 50%, rgba(182,213,195,1) 75%, rgba(194,215,192,1) 75%, rgba(194,215,192,1) 100%);
    background: linear-gradient(to bottom, rgba(135,208,208,1) 0%, rgba(135,208,208,1) 25%, rgba(159,211,201,1) 25%, rgba(159,211,201,1) 50%, rgba(182,213,195,1) 50%, rgba(182,213,195,1) 75%, rgba(194,215,192,1) 75%, rgba(194,215,192,1) 100%);
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#87d0d0', endColorstr='#c2d7c0', GradientType=0 );
}
</style>
